apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wikijs-credentials
spec:
  provider: vault
  secretObjects:
    - secretName: wikijs-credentials
      type: Opaque
      data:
        - objectName: wikijs-password
          key: wikijs-password
        - objectName: postgres-password
          key: postgres-password
  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "wikijs"
    objects: |
      - objectName: "wikijs-password"
        secretPath: "secret/data/infra/wikijs"
        secretKey: "wikijs-password"
      - objectName: "postgres-password"
        secretPath: "secret/data/infra/wikijs"
        secretKey: "postgres-password"

