argo-workflows:
  server:
    serviceAccount:
      name: argo-workflow-server

    volumes:
      - name: argo-workflow-app-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: argo-workflow-app-secrets
    volumeMounts:
      - name: argo-workflow-app-secrets
        mountPath: "/mnt/secrets-store"
        readOnly: true

    sso:
      issuer: https://vault.trial.studio/v1/identity/oidc/provider/argo-workflow
      clientId:
        name: argo-workflow-app-secrets
        key: oidc-client-id
      clientSecret:
        name: argo-workflow-app-secrets
        key: oidc-client-secret
      redirectUrl: https://argo-workflow.trial.studio/oauth2/callback
      rbac:
        enabled: false
        secretWhitelist: []
      insecureSkipVerify: false
      scopes:
        - profile
        - groups
        - email
    extraArgs:
      - --auth-mode=sso
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argo-workflow.trial.studio
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: argo-workflow-cm-tls
          hosts:
            - argo-workflow.trial.studio
