apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authentik-db-credentials
spec:
  provider: vault
  secretObjects:
    - secretName: db-credentials-postgres
      type: kubernetes.io/basic-auth
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: postgres-db-username
          key: username
        - objectName: postgres-db-password
          key: password
    - secretName: db-credentials-authentik
      type: kubernetes.io/basic-auth
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: authentik-db-username
          key: username
        - objectName: authentik-db-password
          key: password
    - secretName: authentik-secret-key
      type: Opaque
      data:
        - objectName: authentik-secret-key
          key: authentik-secret-key
    - secretName: s3-backup-credentials
      type: Opaque
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: s3-backup-access-key-id
          key: s3-backup-access-key-id
        - objectName: s3-backup-secret-access-key
          key: s3-backup-secret-access-key
        - objectName: s3-backup-region
          key: s3-backup-region
    
  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "authentik"
    objects: |
      - objectName: "postgres-db-username"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "postgres-db-username"
      - objectName: "postgres-db-password"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "postgres-db-password"
      - objectName: "authentik-db-username"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "authentik-db-username"
      - objectName: "authentik-db-password"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "authentik-db-password"
      - objectName: "authentik-secret-key"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "authentik-secret-key"
      - objectName: "s3-backup-access-key-id"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "s3-backup-access-key-id"
      - objectName: "s3-backup-secret-access-key"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "s3-backup-secret-access-key"
      - objectName: "s3-backup-region"
        secretPath: "secrets-infra/data/authentik"
        secretKey: "s3-backup-region"
