mimir-distributed:
  alertmanager:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  compactor:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  ingester:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  store_gateway:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  minio:
    persistence:
      storageClass: openebs-hostpath

  nginx:
    ingress:
      enabled: false

  metaMonitoring:
    serviceMonitor:
      enabled: true
    grafanaAgent:
      enabled: true
      installOperator: false
      metrics:
        additionalRemoteWriteConfigs:
          - url: "http://mimir-nginx.observer.svc:80/api/v1/push"
