apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-postgres-credentials
spec:
  provider: vault
  secretObjects:
    - secretName: grafana-postgres-credentials-admin
      type: kubernetes.io/basic-auth
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: postgres-admin-username
          key: username
        - objectName: postgres-admin-password
          key: password
    - secretName: grafana-postgres-credentials-grafana
      type: kubernetes.io/basic-auth
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: postgres-grafana-username
          key: username
        - objectName: postgres-grafana-password
          key: password
    - secretName: s3-backup-credentials-grafana
      type: Opaque
      labels:
        "cnpg.io/reload": "true"
      data:
        - objectName: s3-access-key-id
          key: s3-access-key-id
        - objectName: s3-access-key-secret
          key: s3-access-key-secret
        - objectName: s3-region
          key: s3-region

  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "grafana-postgres-read"
    objects: |
      - objectName: "postgres-admin-username"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "postgres-admin-username"
      - objectName: "postgres-admin-password"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "postgres-admin-password"
      - objectName: "postgres-grafana-username"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "postgres-grafana-username"
      - objectName: "postgres-grafana-password"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "postgres-grafana-password"
      - objectName: "s3-access-key-id"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "s3-access-key-id"
      - objectName: "s3-access-key-secret"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "s3-access-key-secret"
      - objectName: "s3-region"
        secretPath: "secret/data/grafana/postgres"
        secretKey: "s3-region"
