apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-db-cluster
spec:
  # second, minute, hour, day of month, month, day of week
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: grafana-db-cluster