apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oidc-credentials-grafana
spec:
  provider: vault
  secretObjects:
    - secretName: oidc-credentials-grafana
      type: Opaque
      data:
        - objectName: oidc-client-id
          key: oidc-client-id
        - objectName: oidc-client-secret
          key: oidc-client-secret 
  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "oidc-grafana"
    objects: |
      - objectName: "oidc-client-id"
        secretPath: "secrets-oidc/data/grafana"
        secretKey: "oidc-client-id"
      - objectName: "oidc-client-secret"
        secretPath: "secrets-oidc/data/grafana"
        secretKey: "oidc-client-secret"