apiVersion: v1
kind: ServiceAccount
metadata:
  name: spc-container-argo-cd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-container-argo-cd
  labels:
    app: spc-container-argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spc-container-argo-cd
  template:
    metadata:
      name: spc-container-argo-cd
      labels:
        app: spc-container-argo-cd
    spec:
      serviceAccountName: spc-container-argo-cd
      containers:
        - name: spc-container-argo-cd
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
          volumeMounts:
            - mountPath: "/mnt/secret-store"
              name: argo-cd-app-secrets
              readOnly: true
      volumes:
        - name: argo-cd-app-secrets
          csi:
            driver: "secrets-store.csi.k8s.io"
            readOnly: true
            volumeAttributes:
              secretProviderClass: "argo-cd-app-secrets"
      restartPolicy: Always