apiVersion: v1
kind: Pod
metadata:
  name: csi-trigger
  labels:
    app: csi-trigger
spec:
  serviceAccountName: csi-trigger
  containers:
    - name: csi-trigger
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
      volumeMounts:
          - mountPath: "/mnt/secret-store"
            name: secret
            readOnly: true
  volumes:
    - name: secret
      csi:
        driver: "secrets-store.csi.k8s.io"
        readOnly: true
        volumeAttributes:
          secretProviderClass: "oidc-credentials-argo-cd"
  restartPolicy: Always
