apiVersion: v2
name: dashboard
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "6.48.0"
dependencies:
  - name: grafana
    version: 6.48.0
    repository: https://grafana.github.io/helm-charts
