grafana:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - grafana.trial.studio
        secretName: grafana-cm-tls
    hosts:
      - grafana.trial.studio

  serviceAccount:
    name: grafana

  envFromSecret: oidc-credentials-grafana
  extraSecretMounts:
    - name: grafana-credentials
      mountPath: "/mnt/secrets-store"
      readOnly: true
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "oidc-credentials-grafana"

  grafana.ini:
    server:
      domain: grafana.trial.studio
      root_url: https://grafana.trial.studio
      enforce_domain: true
      enable_gzip: true
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: true
      feedback_links_enabled: false
    security:
      disable_initial_admin_creation: true
      disable_gravatar: true
      cookie_secure: true
      strict_transport_security: true
      content_security_policy: true
    dashboards:
      min_refresh_interval: 15s
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      oauth_auto_login: true
    auth.generic_oauth:
      name: vault
      icon: signin
      enabled: true
      client_id: ${oidc-client-id}
      client_secret: ${oidc-client-secret}
      scopes: openid profile groups email
      auth_url: https://vault.trial.studio/ui/vault/identity/oidc/provider/grafana/authorize
      token_url: https://vault.trial.studio/v1/identity/oidc/provider/grafana/token
      api_url: https://vault.trial.studio/v1/identity/oidc/provider/grafana/userinfo
      allow_assign_grafana_admin: true
      role_attribute_path: contains(groups[*], 'grafana-admins') && 'GrafanaAdmin' || 'Viewer'
#      role_attribute_path: contains(groups[*], 'trialstudio:site-reliability-engineer') && 'GrafanaAdmin' || 'Admin'
    log:
      mode: console
    log.console:
      level: debug
    feature_toggles:
      cloudWatchDynamicLabels: false
