grafana:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - grafana.trial.studio
        secretName: grafana-cm-tls
    hosts:
      - grafana.trial.studio

  serviceAccount:
    name: grafana

  envFromSecret: grafana-credentials
  extraSecretMounts:
    - name: grafana-credentials
      mountPath: "/mnt/secrets-store"
      readOnly: true
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "grafana-credentials"

  admin:
    existingSecret: grafana-credentials
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      domain: grafana.trial.studio
      root_url: https://grafana.trial.studio
      enforce_domain: true
      enable_gzip: true
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: true
      feedback_links_enabled: false
    security:
      disable_initial_admin_creation: false
      disable_gravatar: true
      cookie_secure: true
      strict_transport_security: true
      content_security_policy: true
    dashboards:
      min_refresh_interval: 15s
    datasources:
      datasource_limit: 10000
    auth:
      disable_login_form: false
    auth.generic_oauth:
      name: dex
      icon: signin
      enabled: true
      client_id: ${oidc-client-id}
      client_secret: ${oidc-client-secret}
      scopes: openid profile groups email
      auth_url: https://oidc.trial.studio/auth
      token_url: https://oidc.trial.studio/token
      api_url: https://oidc.trial.studio/userinfo
      allow_assign_grafana_admin: true
      role_attribute_path: contains(groups[*], 'trialstudio:site-reliability-engineer') && 'GrafanaAdmin' || 'Admin'
    log:
      mode: console
    log.console:
      level: debug
    feature_toggles:
      cloudWatchDynamicLabels: false
