apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cert-manager-credentials
spec:
  provider: vault
  secretObjects:
    - secretName: cert-manager-credentials
      type: Opaque
      data:
        - objectName: secret-access-key
          key: secret-access-key

  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "cert-manager"
    objects: |
      - objectName: "secret-access-key"
        secretPath: "secrets-infra/data/cert-manager"
        secretKey: "secret-access-key"