apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trial-studio-sre
roleRef:
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: trialstudio:site-reliability-engineers
