apiVersion: v2
name: trace
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.27.7"
dependencies:
  - name: tempo-distributed
    version: 0.27.7
    repository: https://grafana.github.io/helm-charts
