apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: argo-workflow-app-secrets
spec:
  provider: vault
  secretObjects:
    - secretName: argo-workflow-app-secrets
      type: Opaque
      data:
        - objectName: oidc-client-id
          key: oidc-client-id
        - objectName: oidc-client-secret
          key: oidc-client-secret
  parameters:
    vaultAddress: "http://vault-active.secret:8200"
    roleName: "argo-workflow-app-read"
    objects: |
      - objectName: "oidc-client-id"
        secretPath: "secret/data/argo-workflow/app"
        secretKey: "oidc-client-id"
      - objectName: "oidc-client-secret"
        secretPath: "secret/data/argo-workflow/app"
        secretKey: "oidc-client-secret"