dex:
  envVars:
    - name: DEX_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oidc-credentials-dex
          key: oidc-client-id
    - name: DEX_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oidc-credentials-dex
          key: oidc-client-secret
    - name: ARGO_WORKFLOW_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oidc-credentials-argo-workflow
          key: oidc-client-secret
  volumeMounts:
    - mountPath: "/mnt/secret-store-dex"
      name: secret-dex
      readOnly: true
    - mountPath: "/mnt/secret-store-argo-workflow"
      name: secret-argo-workflow
      readOnly: true
  volumes:
    - name: secret-dex
      csi:
        driver: "secrets-store.csi.k8s.io"
        readOnly: true
        volumeAttributes:
          secretProviderClass: "oidc-credentials-dex"
    - name: secret-argo-workflow
      csi:
        driver: "secrets-store.csi.k8s.io"
        readOnly: true
        volumeAttributes:
          secretProviderClass: "oidc-credentials-argo-workflow"
  config:
    issuer: https://authentik.trial.studio/application/o/dex/
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: oidc
        id: authentik
        name: authentik
        config:
          issuer: https://authentik.trial.studio/application/o/dex/
          clientID: $DEX_CLIENT_ID
          clientSecret: $DEX_CLIENT_SECRET
          redirectURI: https://dex.trial.studio/callback
          scopes:
            - profile

    staticClients:
      - id: argo-workflow
        name: argo-workflow
        redirectURIs:
          - https://argo-workflow.trial.studio/oauth2/callback
        secretEnv: ARGO_WORKFLOW_CLIENT_SECRET

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: dex.trial.studio
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - dex.trial.studio
        secretName: dex-cm-tls

