mimir-distributed:
  alertmanager:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  compactor:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  ingester:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  store_gateway:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  minio:
    persistence:
      storageClass: openebs-hostpath

  nginx:
    ingress:
      enabled: true
      annotation:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: mimir.trial.studio
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: mimir-cm-tls
          hosts:
            - mimir.trial.studio

  metaMonitoring:
    serviceMonitor:
      enabled: true
    grafanaAgent:
      enabled: true
      installOperator: false
      metrics:
        additionalRemoteWriteConfigs:
          - url: "http://metric-mimir-nginx/api/v1/push"
