mimir-distributed:
  alertmanager:
    enabled: false
  overrides_exporter:
    enabled: false
  query_scheduler:
    enabled: false

  compactor:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  ingester:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  store_gateway:
    persistentVolume:
      enabled: false
      storageClass: openebs-hostpath

  minio:
    persistence:
      storageClass: openebs-hostpath

  nginx:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: mimir.trial.studio
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: mimir-cm-tls
          hosts:
            - mimir.trial.studio

  metaMonitoring:
    serviceMonitor:
      enabled: false
    grafanaAgent:
      enabled: false
      installOperator: false
      metrics:
        enabled: false
      logs:
        enabled: false